version: "3.9"
services:
  # ============================================================================
  # SERVICES ICSSIM ORIGINAUX (Inchangés)
  # ============================================================================
  pys:
    build: ics-docker/.
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "FactorySimulation.py"]
    container_name: pys
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      fnet:
        ipv4_address: 192.168.1.31
      
  plc1:
    build: ics-docker/.
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "PLC1.py"]
    container_name: plc1
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.11
      fnet:
        ipv4_address: 192.168.1.11
    # Exposition Modbus pour tests - VULNÉRABILITÉ VOLONTAIRE
    ports:
      - "502:502"

  plc2:
    build: ics-docker/.
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "PLC2.py"]
    container_name: plc2
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.12
      fnet:
        ipv4_address: 192.168.1.12
    ports:
      - "503:502"

  hmi1:
    build: ics-docker/.
    stdin_open: true
    tty: true  
    working_dir: /src
    privileged: true
    entrypoint: ["./start.sh", "HMI1.py"]
    container_name: hmi1
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.21

  hmi2:
    build: ics-docker/.
    stdin_open: true
    tty: true 
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "HMI2.py"]
    container_name: hmi2
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.22

  # ============================================================================
  # NOUVEAU HMI3 BOTTLEASEC - Bi-réseau vulnérable
  # ============================================================================
  hmi3:
    build: ics-docker/.
    stdin_open: true
    tty: true 
    privileged: true
    working_dir: /src
    entrypoint: ["./start_hmi3.sh"]
    container_name: hmi3
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      # Réseau supervision (comme ICSSIM original)
      wnet:
        ipv4_address: 192.168.0.23
      # NOUVEAU: Réseau bureau (pont WiFi simulé)
      office_network:
        ipv4_address: 192.168.2.23
    environment:
      - BOTTLEASEC_MODE=emergency
      - WIFI_BRIDGE_ENABLED=true
      - HMI3_ADMIN_PASS=Admin#2025!
      - HMI3_OPERATOR_PASS=Operator#2025!
      - HARDEN_PORTS=true
    cap_add:
      - NET_ADMIN

  # ============================================================================
  # EXTENSION BOTTLEASEC - Zone Bureau (Nouvelle)
  # ============================================================================
  office_pc1:
    build: ics-docker/.
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "python3", "-c", "import time; time.sleep(3600)"]
    container_name: office_pc1
    volumes:
      - ../src:/src
    networks:
      office_network:
        ipv4_address: 192.168.2.10
    environment:
      - PC_ROLE=administrative
      - HARDEN_PORTS=true

  office_pc2:
    build: ics-docker/.
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "python3", "-c", "import time; time.sleep(3600)"]
    container_name: office_pc2
    volumes:
      - ../src:/src
    networks:
      office_network:
        ipv4_address: 192.168.2.11
    environment:
      - PC_ROLE=technical
      - HARDEN_PORTS=true

  # Point d'accès WiFi simulé
  wifi_access_point:
    build: ics-docker/.
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "python3", "-c", "import time; time.sleep(3600)"]
    container_name: wifi_ap
    volumes:
      - ../src:/src
    networks:
      office_network:
        ipv4_address: 192.168.2.1
    environment:
      - DEVICE_TYPE=wifi_access_point
      - SSID=BottleASec_Corporate

  # ============================================================================
  # ATTACKERS ICSSIM + BOTTLEASEC
  # ============================================================================
  attacker:
    build: attacker-docker/.
    stdin_open: true
    privileged: true
    tty: true
    working_dir: /src
    entrypoint: ["./start.sh", "Attacker.py"]
    container_name: attacker
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.42

  attacker2:
    build: attacker-docker/.
    stdin_open: true
    privileged: true
    tty: true
    working_dir: /src
    entrypoint: ["./start.sh", "AttackerMachine.py"]
    container_name: attackermachine
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.41

  attackerremote:
    build: attacker-docker/.
    stdin_open: true
    privileged: true
    tty: true
    working_dir: /src
    entrypoint: [ "./start.sh", "AttackerRemote.py" ]
    container_name: attackerremote
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.43

  # NOUVEAU: Attaquant BottleASec sur réseau bureau
  bottleasec_attacker:
    build: attacker-docker/.
    stdin_open: true
    privileged: true
    tty: true
    working_dir: /src
    entrypoint: ["./start.sh", "Attacker.py"]  # Utilise Attacker existant pour l'instant
    container_name: bottleasec_attacker
    volumes:
      - ../src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      office_network:
        ipv4_address: 192.168.2.100
    environment:
      - ATTACKER_TYPE=bottleasec

# ============================================================================
# RÉSEAUX - Compatible ICSSIM + Extension BottleASec
# ============================================================================
networks:
  # Réseau principal ICSSIM (inchangé)
  wnet:
    driver: bridge
    name: icsnet
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_icsnet

  # Réseau simulation physique ICSSIM (inchangé)  
  fnet:
    driver: bridge
    name: phynet
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1 
    driver_opts:
      com.docker.network.bridge.name: br_phynet

  # NOUVEAU: Réseau bureau BottleASec
  office_network:
    driver: bridge
    name: bottleasec_office
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
    driver_opts:
      com.docker.network.bridge.name: br_office
